# Generated by Django 5.2.4 on 2025-09-22 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0002_chatsession_chat_type_tempdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rag_app.document'),
        ),
    ]
