# Generated by Django 5.2.4 on 2025-10-06 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0002_alter_chatsession_subject_alter_chatsession_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_chats', to='rag_app.document'),
        ),
    ]
