# Generated by Django 4.2.23 on 2025-09-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0003_chatsession_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudySession',
        ),
    ]
