# Generated by Django 4.2.23 on 2025-10-09 07:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0003_alter_chatsession_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_file', models.ImageField(upload_to='document_images/')),
                ('page_number', models.PositiveIntegerField()),
                ('image_index', models.PositiveIntegerField()),
                ('ocr_text', models.TextField(blank=True)),
                ('ocr_processed', models.BooleanField(default=False)),
                ('embedding_vector', models.BinaryField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rag_app.document')),
            ],
            options={
                'ordering': ['page_number', 'image_index'],
                'unique_together': {('document', 'page_number', 'image_index')},
            },
        ),
    ]
