# Generated by Django 4.2.23 on 2025-10-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0004_documentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='processed_text',
            field=models.TextField(blank=True, help_text='Clean text-only version (document text + OCR text)'),
        ),
    ]
