# Generated by Django 5.2.4 on 2025-10-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0004_document_processed_text_document_processing_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempdocument',
            name='processing_mode',
            field=models.CharField(choices=[('fast', 'Fast Processing (Text Only)'), ('ocr', 'Advanced Processing (Text + OCR for Images)')], default='fast', max_length=10),
        ),
    ]
