# Generated by Django 5.2.6 on 2025-09-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0004_remove_study_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='google_form_edit_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='google_form_owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='google_form_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
